Make the package ESM-only
We have ESM package that needs to import ts-results and it's not easy at
the moment because of[1]

    import {Err} from 'ts-results'
            ^^^
    SyntaxError: Named export 'Err' not found. The requested module 'ts-results' is a CommonJS module, which may not support all module.exports as named exports.
    CommonJS modules can always be imported via the default export, for example using:

    import pkg from 'ts-results';
    const {Err} = pkg;

Since time is kind of of the essence and it's easier to make this
package ESM-only instead of trying to figure out how to handle both
CommonJS and ESM client code let's publish an ESM-only version for now.

[1] https://github.com/vultix/ts-results/issues/37